### PR TITLE
Jet variables for 763

### PR DESCRIPTION
**Pull request by alefisico**
Main changes compared to the last version
- Updating all the getByLabel to getByToken (mandatory after 76X)
- Jets are reclustered with the jetToolbox. In the same way, all the substructure variables are now calculated from the toolbox instead of taking the ones from miniAOD
- AK8 Puppi jets, with same content as AK8 CHS jets (again from the jetToolbox)
- Updating JER values
- Adding DataProcessing label for 76X samples

### CODE REVIEW

**Comment by dmajumder** [comment]
@alefisico @rappoccio @skyriacoCMS @jkarancs @decosa 
PR merged.
However new b-taggers (pfCombinedCvsLJetTags, pfCombinedCvsBJetTags, pfBoostedDoubleSecondaryVertexAK8BJetTags, pfBoostedDoubleSecondaryVertexCA15BJetTags) not available in JetToolBox. The double b-tagger is fairly important, can this be prioritised in the next version?

**Comment by rappoccio** [comment]
Hi, Devdatta, 

It can certainly be prioritized in the next version, but we need someone to implement it. The original plan was to have the BTV contact do this, so either you or Ivan ;). 

Cheers,
Sal

**Comment by jmhogan** [comment]
Hi,

We've tested adding pfBoostedDoubleSecondaryVertexAK8BJetTags to
JetToolbox, and all it took was adding the string to the bTagDiscriminators
list:

jetToolbox( process, 'ak8', 'ak8JetSubs', 'out',
            addSoftDrop=True ,
            addSoftDropSubjets=True,
            JETCorrPayload='AK8PFCHS',
            subJETCorrPayload='AK4PFchs',
            JETCorrLevels=['L1FastJet', 'L2Relative', 'L3Absolute'],
            Cut='pt > 200',
            CutSubjet='pt > 20',
            bTagDiscriminators = ['pfTrackCountingHighEffBJetTags',
                                  'pfTrackCountingHighPurBJetTags',
                                  'pfJetProbabilityBJetTags',
                                  'pfJetBProbabilityBJetTags',
                                  'pfSimpleSecondaryVertexHighEffBJetTags',
                                  'pfSimpleSecondaryVertexHighPurBJetTags',
                                  'pfCombinedSecondaryVertexV2BJetTags',

'pfCombinedInclusiveSecondaryVertexV2BJetTags',
                                  '
_pfBoostedDoubleSecondaryVertexAK8BJetTags_'
                                  ]
            )

I imagine this is true for the other taggers as well if they're available
in CMSSW_7_6_whatever.

Julie

On Fri, Feb 5, 2016 at 8:09 AM, rappoccio notifications@github.com wrote:

> Hi, Devdatta,
> 
> It can certainly be prioritized in the next version, but we need someone
> to implement it. The original plan was to have the BTV contact do this, so
> either you or Ivan ;).
> 
> Cheers,
> Sal
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cmsb2g/B2GAnaFW/pull/33#issuecomment-180373676.

## 

_Julie M. Hogan_
Brown University
Dept. of Physics

**Comment by alefisico** [comment]
Hi all,
great, I think we will need just to add the bTagDiscriminators list into the toolbox because the other options are the default values. Let me add them and make a new PR. Is there anything else in that list that I need to include?
bTagDiscriminators = [ 'pfTrackCountingHighEffBJetTags',
                                     'pfTrackCountingHighPurBJetTags',
                                     'pfJetProbabilityBJetTags',
                                     'pfJetBProbabilityBJetTags',
                                     'pfSimpleSecondaryVertexHighEffBJetTags',
                                     'pfSimpleSecondaryVertexHighPurBJetTags',
                                     'pfCombinedSecondaryVertexV2BJetTags',
                                     'pfCombinedInclusiveSecondaryVertexV2BJetTags',
                                     '_pfBoostedDoubleSecondaryVertexAK8BJetTags_'
                                  ]

**Comment by dmajumder** [comment]
Awesome, thanks! We need a topic branch for this?

**Comment by skyriacoCMS** [comment]
Hello All,

I just made a PR with updated EGamma objects .
Let me know if you see something that does not make sense.

Regards,
-Savvas Kyriacou

**Pull request merged**
