### PR TITLE
Adding puppi and jetToolbox for jets

### PR DESCRIPTION
**Pull request by alefisico**

### CODE REVIEW

**Comment by dmajumder** [comment]
@alefisico If this is for 74X MiniAODds, the current developments are all on CMSSW_7_4_X_V8 branch. Better to have the PR there.

**Comment by rappoccio** [comment]
@dmajumder I was thinking we probably want this on the master also, no?

**Comment by dmajumder** [comment]
@rappoccio ITC, we need to bring master up to speed with CMSSW_7_4_V8. May be we rebase?

**Comment by rappoccio** [comment]
@dmajumder Looking at the history it seems that the master is up to date with the branch, no?

**Comment by dmajumder** [comment]
@rappoccio Uh, I thought is is several commits ahead
https://github.com/cmsb2g/B2GAnaFW/compare/master...CMSSW_7_4_X_V8

**Comment by rappoccio** [comment]
Ahh yes, sorry, I was confused with another branch. Sorry about that!

**Pull request merged**
