### PR TITLE
Fixing readme and adding 76X JECs

### PR DESCRIPTION
**Pull request by alefisico**

### CODE REVIEW

**Comment by dmajumder** [comment]
@alefisico 
test/Fall15_25nsV1_DATA.db where does this come from? Do we have data JECs already in 76X?

**Comment by alefisico** [comment]
from here: https://github.com/cms-jet/JECDatabase/tree/master/SQLiteFiles
I think they are still testing the DATA JECs, but at least according to this:
https://hypernews.cern.ch/HyperNews/CMS/get/jes/581.html
the MC are ready.

**Comment by dmajumder** [comment]
Yes the MC is ready and was announced, but we should probably hold off committing the data JEC sqlite file

**Comment by alefisico** [comment]
agree, but we are still testing this recipe, right? I just added it to test.

**Comment by dmajumder** [comment]
@alefisico We are almost ready for a production tag. At this stage only standard stuff should be on this branch. I guess you are testing on your fork, right? If you want you can create a test brach here.

**Comment by alefisico** [comment]
@dmajumder so do you want me to remove the PR?

**Comment by dmajumder** [comment]
@alefisico not the whole PR, just modify it by removing test/Fall15_25nsV1_DATA.db

**Comment by alefisico** [comment]
@dmajumder hey, maybe you didn't see it, but I remove what you suggested 2 days ago. Do we have any plans to start creating this Nutples?

**Pull request merged**
